name: build-github-pages
env:
  GITHUB_ACTOR: BackofenLab
  GITHUB_REPOSITORY: BackofenLab/V_RNA-pages
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_rmarkdown_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Setup R environment and install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
          mkdir -p ~/R/Library
          Rscript -e ".libPaths('~/R/Library'); install.packages(c('rmarkdown', 'flextable', 'officer'), repos='https://cloud.r-project.org/')"
        
      - name: Render Rmarkdown
        run: Rscript -e ".libPaths('~/R/Library'); rmarkdown::render_site()"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'docs/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
